#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}

set -x

wclean ./src_acoustics
wclean ./solver_dualZoneBuoyantPimpleFoam
wclean ./solver_dualZoneEulerFoam

# ----------------------------------------------------------------- end-of-file
