#!/bin/sh

cd ${0%/*} || exit 1    # run from this directory

makeType=${1:-libso}
set -x

wmake ./src_acoustics
wmake ./solver_dualZoneBuoyantPimpleFoam
wmake ./solver_dualZoneEulerFoam

# ----------------------------------------------------------------- end-of-file
